"""Canonical term and phrase vocab for deterministic ATS extraction."""

from __future__ import annotations

CANONICAL_TERM_MAP = {
    "api": "api",
    "apis": "api",
    "ci/cd": "ci/cd",
    "javascript": "javascript",
    "js": "javascript",
    "k8s": "kubernetes",
    "node.js": "node.js",
    "nodejs": "node.js",
    "postgres": "postgresql",
    "postgresql": "postgresql",
    "react": "react",
    "reactjs": "react",
    "ts": "typescript",
    "typescript": "typescript",
}

CANONICAL_PHRASE_MAP = {
    "c sharp": "c#",
    "ci cd": "ci/cd",
    "ci/cd": "ci/cd",
    "computer science": "computer science",
    "customer inquiries": "customer inquiries",
    "customer service": "customer service",
    "data pipeline": "data pipeline",
    "data pipelines": "data pipeline",
    "dot net": ".net",
    "clean sales floor": "showroom cleanliness",
    "machine learning": "machine learning",
    "merchandising displays": "merchandising displays",
    "node js": "node.js",
    "payment processing": "sales transactions",
    "pos transaction": "sales transactions",
    "pos transactions": "sales transactions",
    "product displays": "merchandising displays",
    "product selection": "product selection",
    "react js": "react",
    "retail operations": "retail operations",
    "rest api": "rest api",
    "rest apis": "rest api",
    "restful api": "rest api",
    "restful apis": "rest api",
    "sales transaction": "sales transactions",
    "sales transactions": "sales transactions",
    "showroom cleanliness": "showroom cleanliness",
    "software engineer": "software engineer",
    "weekend availability": "weekend availability",
}

PROTECTED_PHRASES = frozenset(
    {
        ".net",
        "computer science",
        "customer inquiries",
        "customer service",
        "data pipeline",
        "machine learning",
        "merchandising displays",
        "product selection",
        "retail operations",
        "rest api",
        "sales transactions",
        "showroom cleanliness",
        "software engineer",
        "weekend availability",
    }
)

PHRASE_HEADWORDS = frozenset(
    {
        "analyst",
        "api",
        "apis",
        "architect",
        "automation",
        "cloud",
        "database",
        "developer",
        "engineer",
        "framework",
        "infrastructure",
        "inquiries",
        "learning",
        "manager",
        "microservices",
        "pipeline",
        "pipelines",
        "platform",
        "selection",
        "transactions",
        "scientist",
        "security",
        "service",
        "services",
        "stack",
        "cleanliness",
        "systems",
        "availability",
        "operations",
    }
)
